# -*- coding: utf-8 -*-
"""Replication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15c3FcasRswz-1vj6v7Bqhm3BCJfpdAPq
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/JaehaKim97/SR4IR.git
# %cd SR4IR

from google.colab import drive
drive.mount('/content/drive')

!cp "/content/drive/MyDrive/archive.zip" /content/

!unzip -q /content/archive.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR

!rm -rf datasets/StanfordCars

!ls -lh /content/archive.zip

!apt-get update -qq
!apt-get install -y p7zip-full

!7z x "/content/archive.zip" -o/content/

!ls /content
!ls /content/car_data
!ls /content/car_data/car_data

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR

!rm -rf datasets/StanfordCars

import shutil

shutil.copytree(
    "/content/car_data/car_data/train",
    "datasets/StanfordCars/train"
)

shutil.copytree(
    "/content/car_data/car_data/test",
    "datasets/StanfordCars/val"
)

print("Stanford Cars dataset ready for SR4IR ✅")

!ls datasets/StanfordCars/train | head
!ls "datasets/StanfordCars/train/Acura Integra Type R 2001" | head

import yaml

cfg_path = "options/cls/StanfordCars/134_SR4IR_swinir_x4.yml"

cfg = yaml.safe_load(open(cfg_path))
cfg["test"]["batch_size"] = 8
cfg["num_threads"] = 2

yaml.dump(cfg, open(cfg_path,"w"))

print("Config updated ✅")

!pip install lpips

!pip install ptflops

!unzip -o /content/cls_train.zip

!rm -rf experiments/cls/134_SR4IR_swinir_x4
!mv cls/134_SR4IR_swinir_x4 experiments/cls/

!ls experiments/cls/134_SR4IR_swinir_x4/models

!CUDA_VISIBLE_DEVICES=0 python src/main.py \
-opt options/cls/StanfordCars/134_SR4IR_swinir_x4.yml \
--test_only

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR

import sys
sys.path.append("/content/SR4IR/src")

!ls src/archs

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR

!rm -rf experiments/cls/134_SR4IR_swinir_x4*

!unzip -o /content/cls_train.zip

!mkdir -p experiments/cls
!mv cls/134_SR4IR_swinir_x4 experiments/cls/

!ls experiments/cls/134_SR4IR_swinir_x4/models

!CUDA_VISIBLE_DEVICES=0 python src/main.py \
-opt options/cls/StanfordCars/134_SR4IR_swinir_x4.yml \
--test_only

!ls vis_results

import matplotlib.pyplot as plt
import glob
from PIL import Image

sr_imgs = sorted(glob.glob("vis_results/*_SR.png"))

print("Total SR images saved:", len(sr_imgs))

plt.figure(figsize=(12,30))

for i, sr_path in enumerate(sr_imgs):

    lr = Image.open(sr_path.replace("_SR","_LR"))
    sr = Image.open(sr_path)
    hr = Image.open(sr_path.replace("_SR","_HR"))

    plt.subplot(len(sr_imgs),3,3*i+1)
    plt.imshow(lr)
    plt.title("LR")
    plt.axis("off")

    plt.subplot(len(sr_imgs),3,3*i+2)
    plt.imshow(sr)
    plt.title("SR4IR")
    plt.axis("off")

    plt.subplot(len(sr_imgs),3,3*i+3)
    plt.imshow(hr)
    plt.title("HR")
    plt.axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import glob
from PIL import Image

sr_imgs = sorted(glob.glob("vis_results/*_SR.png"))

for sr_path in sr_imgs:

    lr = Image.open(sr_path.replace("_SR","_LR"))
    sr = Image.open(sr_path)
    hr = Image.open(sr_path.replace("_SR","_HR"))

    plt.figure(figsize=(15,5))

    plt.subplot(1,3,1)
    plt.imshow(lr)
    plt.title("LR (input)")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(sr)
    plt.title("SR4IR output")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(hr)
    plt.title("HR ground truth")
    plt.axis("off")

    plt.show()

import matplotlib.pyplot as plt
import glob
from PIL import Image

sr_imgs = sorted(glob.glob("vis_results/*_SR.png"))

ZOOM = 4          # zoom factor
PATCH = 120       # patch size

for sr_path in sr_imgs:

    lr = Image.open(sr_path.replace("_SR","_LR"))
    sr = Image.open(sr_path)
    hr = Image.open(sr_path.replace("_SR","_HR"))

    # ---- choose center patch ----
    w, h = hr.size
    cx, cy = w//2, h//2

    box = (
        cx - PATCH//2,
        cy - PATCH//2,
        cx + PATCH//2,
        cy + PATCH//2
    )

    lr_p = lr.crop(box).resize((PATCH*ZOOM, PATCH*ZOOM), Image.NEAREST)
    sr_p = sr.crop(box).resize((PATCH*ZOOM, PATCH*ZOOM), Image.NEAREST)
    hr_p = hr.crop(box).resize((PATCH*ZOOM, PATCH*ZOOM), Image.NEAREST)

    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(lr_p)
    plt.title("LR (zoomed patch)")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(sr_p)
    plt.title("SR4IR (zoomed patch)")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(hr_p)
    plt.title("HR (zoomed patch)")
    plt.axis("off")

    plt.show()

import matplotlib.pyplot as plt
import glob
from PIL import Image

sr_imgs = sorted(glob.glob("vis_results/*_SR.png"))

for i, sr_path in enumerate(sr_imgs):

    lr = Image.open(sr_path.replace("_SR","_LR"))
    sr = Image.open(sr_path)
    hr = Image.open(sr_path.replace("_SR","_HR"))

    plt.figure(figsize=(6,12))

    plt.subplot(3,1,1)
    plt.imshow(lr)
    plt.title(f"Sample {i} — LR input")
    plt.axis("off")

    plt.subplot(3,1,2)
    plt.imshow(sr)
    plt.title("SR4IR output")
    plt.axis("off")

    plt.subplot(3,1,3)
    plt.imshow(hr)
    plt.title("HR ground truth")
    plt.axis("off")

    plt.tight_layout()
    plt.show()