# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113q7KQtBe01VnoYQ4Fc9NLTyuBvyyqQg
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/JaehaKim97/SR4IR
# %cd SR4IR

!pip install lpips

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
import lpips
import os

from google.colab import drive
drive.mount('/content/drive')

import os

folder_path = "/content/drive/MyDrive/car_dataset"
print(os.listdir(folder_path))

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR

!pip install ptflops

from ptflops import get_model_complexity_info

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR/src

!python main.py -opt ../options/cls/StanfordCars/114_SR4IR_edsr_x4.yml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SR4IR/src

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import yaml

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

transform = transforms.Compose([
    transforms.Resize((160,160)),
    transforms.ToTensor()
])

test_dataset = datasets.ImageFolder(
    root="/content/drive/MyDrive/car_dataset/test",
    transform=transform
)

test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

print("Number of test images:", len(test_dataset))
print("Classes:", test_dataset.classes)

from models.cls.sr4ir_cls_model import SR4IRClassificationModel

opt_path = "../options/cls/StanfordCars/114_SR4IR_edsr_x4.yml"

with open(opt_path, 'r') as f:
    opt = yaml.safe_load(f)


opt['dist'] = False
opt['rank'] = 0
opt['world_size'] = 1

model = SR4IRClassificationModel(opt)

model_path = "/content/net_cls_epoch_30.pth"

model.net_cls.load_state_dict(torch.load(model_path))
model.net_cls.to(device)
model.net_cls.eval()

print("Model loaded successfully")

correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model.net_cls(images)
        _, preds = outputs.max(1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

acc = 100 * correct / total

print(f"\n Test Accuracy: {acc:.2f}%")

import matplotlib.pyplot as plt

images, labels = next(iter(test_loader))
images = images.to(device)

outputs = model.net_cls(images)
_, preds = outputs.max(1)

for i in range(5):
    plt.imshow(images[i].cpu().permute(1,2,0))
    plt.title(f"Pred: {test_dataset.classes[preds[i]]}")
    plt.axis('off')
    plt.show()

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model.net_cls(images)
        _, preds = outputs.max(1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

print("Predictions collected")

cm = confusion_matrix(all_labels, all_preds)

print("Confusion Matrix:\n", cm)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))

sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=test_dataset.classes,
            yticklabels=test_dataset.classes,
            cmap='Blues')

plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()